---
title: "Cowcod and Bocaccio Navigaion Summary"
author: "Kevin L. Stierhoff"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
# Install and load pacman (library management package)
if (!require("pacman")) install.packages("pacman")

# Install and load required packages from CRAN ---------------------------------
pacman::p_load(tidyverse,lubridate,knitr,cowplot,
               here,leaflet,leafem,htmltools,
               mapview,fs,DT,xml2,DBI,odbc,bookdown,sf)

knitr::opts_chunk$set(echo = TRUE)

theme_set(theme_bw())

# Controls
get.db <- T
```

```{r extract-database}
# Read dives of interest
dive_list <- read_csv(here("Data/tbl_Elan_dives.csv")) %>% 
  pull()

if (get.db) {
  # Set up database connection
  con  <- dbConnect(odbc::odbc(), 
                    Driver = "SQL Server", 
                    Server = "161.55.235.187", 
                    Database = "ROV2", 
                    timeout = 10,
                    Trusted_Connection = "True")

  # Create pointers
  logs <- tbl(con, "tbl_LOGS") %>%
    select(-comments) %>%
    collect() %>% 
    filter(dive_name %in% dive_list)

  # Get nav data
  nav <- tbl(con, "tbl_NAV") %>% 
    left_join(select(logs, dive_name, site_general), copy = TRUE) %>% 
    filter(!is.na(site_general)) %>% 
    collect()

  obs <- tbl(con, "tbl_VIDEO_OBS") %>% 
    select(-comments) %>% 
    left_join(select(logs, dive_name, site_general), copy = TRUE) %>% 
    filter(!is.na(site_general)) %>% 
    collect()
  
  spp <- tbl(con, "tlu_SPECIES_CODES") %>% 
    collect()
  
  # Close connection
  dbDisconnect(con)
  
  save(logs, nav, obs, spp,
       file = here("Data/rov_data_elan.Rdata"))
} else {
  load(here("Data/rov_data_elan.Rdata"))
}
```

```{r}
nav.depth.summ <- nav %>% 
  filter(depth != -999) %>% 
  mutate(depth.bin = cut(depth, seq(-600, 0, 2))) %>% 
  group_by(dive_name, depth.bin) %>%
  summarise(distance = round(sum(disp_r)),
            duration = round(as.numeric(sum(xts::diff.xts(date_time), na.rm = TRUE))/60))

nav.depth.summ2 <- nav.depth.summ %>% 
  summarise(distance = sum(distance),
            duration = sum(duration))


write_csv(nav.depth.summ, here("Output/nav_depth_summary_bin.csv"))
write_csv(nav.depth.summ2, here("Output/nav_depth_summary_dive.csv"))

hist(nav.depth.summ2$distance)
hist(nav.depth.summ2$duration)
```

s
